### ISSUE TITLE
Folder icon is changed

### ISSUE THREAD

**Issue by koddsson** [xxhomey19/github-file-icon#12]
Not sure if this is by design but some folders have their icon switched out like this:

![image](https://user-images.githubusercontent.com/318208/34721453-b25148ea-f53a-11e7-9ce0-aaa91e666263.png)

To me, the `.github/` folder in the screenshot should still have the folder icon but I could be alone in that opinion. Would you accept a PR to make sure we don't change the folder icons or at least provide the option to change the behaviour for people that would like to keep the folder icons intact?

**Comment by xxhomey19** [comment]
Yes, some icons of folder with specific name will be changed. I used [file-icons-js](https://github.com/websemantics/file-icons-js) to determine the icon by the its name, and I didn't identify whether the name is a file or a folder.
It's okay to not change the folder icons! PRs are welcome.

**Comment by koddsson** [comment]
Hey @xxhomey19. I was going to take a stab at this but I can't get the extension running locally. It's just a matter of checking out the code, running `npm install && npm run build` and loading the `build/` folder as a unpackaged extension in chrome, right?

**Comment by xxhomey19** [comment]
Yes, that’s right. Doesn’t it work?

**Comment by MichielDx** [comment]
Doesn't work for me either after the pjax merge

**Comment by xxhomey19** [comment]
😕 That’s strange. Does it show any error message? Btw, my node version is 9.2.1.

**Comment by koddsson** [comment]
It happened kind of sparatically for me. Just when building and loading the extension unpacked tho. I disabled some other github extensions and it worked a bit better but I'm not sure what that was.
