### ISSUE TITLE
Disappear from AMO?

### ISSUE THREAD

**Issue by gluons** [xxhomey19/github-file-icon#19]
I revisit AMO today and I can't see this [add-on page](https://addons.mozilla.org/en-US/firefox/addon/github-file-icon/).

![default](https://user-images.githubusercontent.com/4688092/35180222-3f6f8074-fdde-11e7-80d8-9928b33bc74c.PNG)

**Comment by xxhomey19** [comment]
Yes, I got `We generally don't accept using the 'eval' function.` from their review.
I'm trying to fix it, but haven't find a good solution.

**Comment by gluons** [comment]
It's back now. 🎉

![Hooray](https://media.giphy.com/media/MhHXeM4SpKrpC/giphy.gif)


![AMO](https://user-images.githubusercontent.com/4688092/35224375-6173b390-ffb7-11e7-83a2-83470d18f01d.PNG)
