### ISSUE TITLE
Support Github Enterprise

### ISSUE THREAD

**Issue by raphaeleidus** [xxhomey19/github-file-icon#2]
Ideally in the same way this works: https://github.com/buunguyen/octotree#enterprise-urls

**Comment by xxhomey19** [comment]
@raphaeleidus 
Sorry I haven't used GitHub enterprise before, and I don't have enterprise account. Therefore, I could be difficult for me to develop.
Hope someone could help this issue out.

**Comment by MichielDx** [comment]
I'll take a look at this, after fixing gitlab and bitbucket

**Comment by matchai** [comment]
I'm a fan of how it was handled as a Browser Action in Refined GitHub: https://github.com/sindresorhus/refined-github/pull/819.
Less clicks, less copy-pasting, all-around simpler.

**Comment by NickCraver** [comment]
I'm happy to test anything here, as I'd love to see it on Enterprise as well. The UI is nearly identical, and should be for everywhere this is. I agree with @matchai the way Refined GitHub works (where you're simply prompted for a domain) works very well. Ultimately all we're doing is adding a domain of where this extension runs.

**Comment by charliegroll** [comment]
Any update on this?

**Comment by xxhomey19** [comment]
@charliegroll So far, nop.
Would you want to take it?

**Comment by franklinyu** [comment]
Both GitLab and BitBucket support self-hosting. If GitHub Enterprise is supported, I think it would be easy to also support self-hosted GitLab and BitBucket.

**Comment by stamminator** [comment]
@franklinyu, gotcha, so when the user is entering their custom URL, they'll also need to select which product they're using from a drop-down or something. These custom URLs can be stored as an array of `{ url: 'enterprise.domain.com', provider: 'github' }` objects, just as a concept.

**Comment by fregante** [comment]
To add support for custom domains, this is all you need:

```sh
npm i webext-domain-permission-toggle webext-dynamic-content-scripts
```

```js
// in background.js
import 'webext-dynamic-content-scripts';
import addDomainPermissionToggle from 'webext-domain-permission-toggle';

addDomainPermissionToggle();
```

You'll also be able to drop the `tabs` and `webNavigation` permissions, together with: 

https://github.com/xxhomey19/github-file-icon/blob/a525d94786258b707546abe42b8d5b77dbd1284f/src/js/background.js#L14-L18

I'm sending a PR
