### ISSUE TITLE
Addon doesn't work on Github mobile layout

### ISSUE THREAD

**Issue by RoiEXLab** [xxhomey19/github-file-icon#23]
Nice Addon. Didn't knew I needed this until I saw it.
However I noticed it doesn't seem to work on my android phone using the mobile layout of Github (the desktop version works without problems)

**Comment by gluons** [comment]
Seem that it doesn't support mobile site yet.

GitHub use `tr.js-navigation-item > td.icon > .octicon` element as icon in Desktop Site.
But in Mobile Site, it is `a.list-item > .octicon`.

**Comment by xxhomey19** [comment]
Cool I don't notice this issue.
I would fix it when I have spare time, but PRs are welcome!
