### ISSUE TITLE
firefox add-on disapeared 

### ISSUE THREAD

**Issue by g-harel** [xxhomey19/github-file-icon#24]

**Comment by divyanshu013** [comment]
Would be great to have this in firefox. Thanks!

**Comment by xxhomey19** [comment]
Yes, firefox send me a email which said that I use webpack to uglify source code isn't safe. It's really annoying, but I will fix it anyway.

**Comment by divyanshu013** [comment]
That's weird 🤔

**Comment by gluons** [comment]
It's used to happenn in #19. 😢

**Comment by gluons** [comment]
> use webpack to uglify source code isn't safe

Because of `eval` again?

![selection_001](https://user-images.githubusercontent.com/4688092/36354621-e1df2af2-1509-11e8-9e08-f8e52a765e8d.png)

**Comment by xxhomey19** [comment]
It should be available now. I just submit a new version add-on with a instruction file which explains how to build the add-on. Hope firefox won't disable this again.

**Comment by gluons** [comment]
Yeah! It back now.
