### ISSUE TITLE
Code Climate icon is wrong color

### ISSUE THREAD

**Issue by mattaningram** [xxhomey19/github-file-icon#25]
The Code Climate icon should be black, not green. Source: I am lead designer at Code Climate.

![image](https://user-images.githubusercontent.com/955092/36111957-ea81b4d6-0ff5-11e8-96d1-ce9fb11376c2.png)

**Comment by xxhomey19** [comment]
Hi @mattaningram 
Actually, the color of Code Climate icon actually isn't decided by me. I used (file-icons-js)[https://github.com/websemantics/file-icons-js] to change GitHub original icon. So I believe you could open this issue to that repo would be better!

**Comment by mattaningram** [comment]
@xxhomey19 Ah good to know! I'll close this and open it there. Thanks!
