### ISSUE TITLE
Icons flashing issue

### ISSUE THREAD

**Issue by aj-4** [xxhomey19/github-file-icon#3]
Icons will show briefly and disappear on initial page load.
They work as expect on refresh and with cached pages.

It seems they are being loaded then replaced by the default svg graphic.
Are others having this issue?

**Comment by seanhamlin** [comment]
Yeap, seeing the same issue too.

**Comment by xxhomey19** [comment]
So do I. GitHub somehow rerenders page, and it makes this extension useless at the first time.
I will try to find a listener api to detect when the page is reloaded, then call `contentscript.js` again.

**Comment by xxhomey19** [comment]
I have tried a workaround way is to replace icons after delay 500 ms.
Although final result is correct, this will cause icons to flash twice.
I couldn't think of alternative ways to solve this problem at this moment 😢

**Comment by aj-4** [comment]
would you mind pushing that workaround? wouldn't mind a double flash :)

**Comment by xxhomey19** [comment]
Sure.
https://github.com/xxhomey19/github-file-icon/blob/6d1fced4dae432912ebfd5f6d8b1e05679c30d79/src/js/contentscript.js#L6

**Comment by aj-4** [comment]
@xxhomey19 imo that'd be a great workaround

**Comment by xxhomey19** [comment]
@aj-4 Me too. I'm still trying to find a better solution.
