### ISSUE TITLE
Support gitlab/bitbucket?

### ISSUE THREAD

**Issue by MichielDx** [xxhomey19/github-file-icon#4]

**Comment by xxhomey19** [comment]
I haven't used them for long time.
Would you want to send a PR 😄 ?

**Comment by selfup** [comment]
As well as gogs and gitea 😄

**Comment by MichielDx** [comment]
I'll try for gitlab and bitbucket, but I'm don't know how to test it locally 😄

I also get this error when build and starting:

```             
              ...JSON.parse(content.toString()),
              ^^^
SyntaxError: Unexpected token ...
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
```

**Comment by xxhomey19** [comment]
Just run `npm run start`, then webpack will auto reload when you save changes.
What's your nodejs version in your local computer?

**Comment by MichielDx** [comment]
My node version is 6.9.2

I'm not home atm, so I will try that out later

**Comment by MichielDx** [comment]
Just ran `npm run start` and it gives the same error

**Comment by xxhomey19** [comment]
That's strange...
Spread operator should be okay after version 6. Could you delete `node_modules` and run `yarn` to reintall everything again? I couldn't figure out what anything else causes this problem.

**Comment by MichielDx** [comment]
Okay, so I did what you said but it didn't work. After reinstalling node it worked

**Comment by xxhomey19** [comment]
Awesome!

**Comment by MichielDx** [comment]
I'm not sure how to test it locally though, sorry

**Comment by MichielDx** [comment]
oops Accidently closed this

**Comment by xxhomey19** [comment]
Check this
https://developer.chrome.com/extensions/getstarted#unpacked

Select `/build` directory which is build by webpack on the last step.

**Comment by MichielDx** [comment]
Okay, for some reason even when I remove the git url check it still doesn't work on gitlab or bitbucket. And it doesn't show under contentscripts when I check the sources...

Sorry for all the questions, never worked on an extension before 😄

**Comment by xxhomey19** [comment]
No worries. According to [here](https://developer.chrome.com/extensions/content_scripts), property `matches` is required. You could change it to gitlab or bitbucket url. It means `content_scripts` should be injected when you open those websites.

**Comment by MichielDx** [comment]
Got gitlab and bitbucket working, but I get a 403 when trying to push to new branch

**Comment by selfup** [comment]
@MichielDx did you fork? Sounds like you are pushing directly to this repo

**Comment by MichielDx** [comment]
Oh, didn't know you had to do that :sweat_smile: 
First time doing this

**Comment by selfup** [comment]
Yep no worries :+1: 

Happens to everyone :stuck_out_tongue:
