### ISSUE TITLE
Why is browser history permission needed?

### ISSUE THREAD

**Issue by jorgegonzalez** [xxhomey19/github-file-icon#42]
![image](https://user-images.githubusercontent.com/12901172/45130110-48695800-b155-11e8-8047-87b10bb88d61.png)

These are the permissions requested by this extension in Chrome. I'm just wondering why browsing history is requested?

**Comment by xxhomey19** [comment]
Oh that's a legacy code. I'll fix it. Thanks for reporting issue!

**Comment by xxhomey19** [comment]
Hi @jorgegonzalez 
Sorry I made a mistake. I thought it was legacy code, but I found we still need that afterward. Please check #44 for more details.
