### ISSUE TITLE
Performance Issues on Firefox

### ISSUE THREAD

**Issue by Riajyuu** [xxhomey19/github-file-icon#45]
On Firefox, this addon significantly slows down file list loading on my laptop (8G A8 AMD & 8G RAM)

**Comment by xxhomey19** [comment]
Can you provide more details? Like CPU or memory stats.

**Comment by xxhomey19** [comment]
@silverwind 
Thanks for your suggestion! I just tried to use that property (its default value is `"document_idle"`), and here is the result.

Using `"document_start"`:
1. on Chrome: it doesn't work, the program can't select any element from the DOM.
2. on Firefox: it works and improve the speed a lot, but sometimes it can't select any element from the DOM.

Using `"document_end"`:
It works for both browsers but doesn't improve the speed much (at least I can't feel any difference)

@silverwind any thought?

**Comment by xxhomey19** [comment]
@Riajyuu @silverwind 
I just upload the new version v0.7.1
Please try it and see whether it improves the performance.

**Comment by silverwind** [comment]
Thanks, this is much better. Takes maybe a few hundret miliseconds now.
