### ISSUE TITLE
Question: Why settings in Popup menu?

### ISSUE THREAD

**Issue by Jackymancs4** [xxhomey19/github-file-icon#50]
Hello @xxhomey19 
Only now I noted this change, introduced by https://github.com/xxhomey19/github-file-icon/commit/91fce311fbf21fa061fe8f0bf22fbd64e2398d9a.

I was wondering if you can share the rationale behind your decision. It feels to me a little "wrong" to move settings from a place meant for settings to a place like the user popup, meant instad to provide high level interaction and to show off-page informations.

Given the static nature of the addon and the relatively low frequency of settings change I thing most users do, I think having one more action icon is a pretty much uneeded. Just a thought of mine.

Thanks.

**Comment by xxhomey19** [comment]
Hi @Jackymancs4 
It used to be in the option page. At that moment I thought modifying the settings in the action page is more intuitively than modifying it in the option page. Actually, I'm not quite confident about that decision now haha.
I take a look at other extensions I have installed, and I found some of them put their settings in the action page as well. So in my view, it's fine to either put it in the action or the option page. I'm ok with anything.

**Comment by xxhomey19** [comment]
I’m closing this issue because it has been inactive for a few months.

**Comment by xxhomey19** [comment]
The popup window is changed on version 0.8.0. After referring to a few extensions, I believe showing options in a [context menu](https://developer.chrome.com/apps/contextMenus) is more correct than a customized popup menu.

**Comment by xxhomey19** [comment]
Hi @testman42 
Right, I agree with your points, and I guess `contexts: ['all']` may be a mistake. Furethermore, I probly should add `documentUrlPatterns` option to restrict the context menu to only show up on specific pages. I'll fix it asap. Many thanks!

**Comment by xxhomey19** [comment]
@testman42 The changes have been made on version 0.8.1
