### ISSUE TITLE
Wrong file icons on GitHub with submodules?

### ISSUE THREAD

**Issue by auscompgeek** [xxhomey19/github-file-icon#51]
Similar to #39, but on GitHub.

Example repo: https://github.com/ValveSoftware/Proton

**Comment by xxhomey19** [comment]
Thanks mate. You always find bugs of this extension haha.

**Comment by xxhomey19** [comment]
Hi @auscompgeek 
please upgrade to v0.7.2, it looks fine now
![screen shot 2018-11-01 at 21 24 33](https://user-images.githubusercontent.com/12113222/47851790-cd0ee480-de2d-11e8-85dd-89511ee5e6c5.png)
