### ISSUE TITLE
Icon colors

### ISSUE THREAD

**Issue by GrosBourrin** [xxhomey19/github-file-icon#53]
Icons colors are sometimes not easy to see on dark themes of github ! i use a stylish css script to darken github but that's only a suggestion

**Comment by xxhomey19** [comment]
There's an optional style for the dark theme on GitHub. Do you turn it on?
https://github.com/xxhomey19/github-file-icon#turn-on-dark-mode

**Comment by xxhomey19** [comment]
I’m closing this issue because it has been inactive for a few months.
