### ISSUE TITLE
GitLab added another row

### ISSUE THREAD

**Issue by FranklinYu** [xxhomey19/github-file-icon#54]
They added an item `..`, so currently the icon for `i`th item should have been the one for `i - 1`th. This issue only occur in sub-folder; there is no `..` in project root folder.

**Comment by xxhomey19** [comment]
Hi @franklinyu 
thanks for reporting, but I couldn't find any repo which has an item `..`. Could you paste the link of a sample repo and a screenshot for it? Thanks

**Comment by franklinyu** [comment]
That's basically in any project. Like https://gitlab.com/gitlab-org/gitlab-ce/tree/master/scripts

![capture](https://user-images.githubusercontent.com/3153452/48213870-be07c500-e34c-11e8-8c40-134defeca165.PNG)

**Comment by xxhomey19** [comment]
Got it! I'll fix it as soon as possible 👍
