### ISSUE TITLE
Feature Request: Enable on self-hosted GitLab

### ISSUE THREAD

**Issue by TimoSta** [xxhomey19/github-file-icon#55]
We are running a self-hosted internal GitLab instance, on a custom domain.
This extension only seems to apply to the hosted, public GitLab instance at gitlab.com.

It would be great if we'd be able to configure this extension to also cover our use case.

**Comment by xxhomey19** [comment]
This is related to #2 
Once the functionality of entering custom domains is finished, the extension can apply to all private git servers.
