### ISSUE TITLE
Swift icons should be orange

### ISSUE THREAD

**Issue by lukaskollmer** [xxhomey19/github-file-icon#8]
Currently, `.swift` files are represented by a green icon. However, the official Swift logo is the orange bird.
The exact color seems to be `#DF5C43`

<img width="1011" alt="screen shot 2018-01-08 at 22 18 52" src="https://user-images.githubusercontent.com/6547384/34692900-05ea16e0-f4c2-11e7-979a-e2dfe0b9a73a.png">

**Official Swift logo from [swift.org](https://swift.org):**
![](https://swift.org/assets/images/swift.svg)

**Comment by xxhomey19** [comment]
Hi @lukaskollmer 
well, the color of Swift icon actually isn't decided by me. I used [file-icons-js](https://github.com/websemantics/file-icons-js) to create new icons and found it decided to set green color for `.swift` files. Check its code [here](https://github.com/websemantics/file-icons-js/blob/master/index.js#L1250).
So I think this issue should be posted there, it's out of my control sorry.
