### ISSUE TITLE
use default cursor on icon

### ISSUE THREAD

**Issue by tiansh** [xxhomey19/github-file-icon#9]
Hover on icon should keep cursor as default (typically an arrow) instead of cursor for text (a letter I).

**Comment by xxhomey19** [comment]
Really? Originally, it's a svg tag, and it doesn't have `cursor: pointer` css property.

**Comment by tiansh** [comment]
Yes, but default pointer is the auto value for `<img>` and `<svg>` tags, so no need `cursor: pointer` originally.

**Comment by xxhomey19** [comment]
Oh I got your point. However, in my browser, my cursor is an arrow when hovering on icons.
What's your browser and computer OS? I use Chrome and OS X.

**Comment by tiansh** [comment]
Firefox + Windows

    Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:52.0) Gecko/20100101 Firefox/52.0

(Just don't know how to make it work on my Chrome...)
